version: "3.9"
services:
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # If you want to use Postgres, uncomment the following and adjust .env
      # DATABASE_URL: postgres://postgres:postgres@db:5432/signature_app
      # DB_PROVIDER: postgresql
      NEXTAUTH_URL: http://localhost:3000
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signature_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
